-- ============================================================
-- OPE_SQUAD — Migration 001: Initial Schema
-- Created: 2026-02-27
-- Tables: generated_content
-- ============================================================

-- Main table: content generated by the AI engine
-- user_id is the Clerk user ID (not Supabase Auth)
CREATE TABLE IF NOT EXISTS public.generated_content (
  id          uuid DEFAULT gen_random_uuid() PRIMARY KEY,
  user_id     text        NOT NULL,  -- Clerk user ID
  platform    text        NOT NULL,  -- instagram | linkedin | twitter | email
  topic       text        NOT NULL,  -- post topic
  content     text        NOT NULL,  -- generated content
  created_at  timestamptz DEFAULT now() NOT NULL
);

-- Index to speed up queries by user (most common query)
CREATE INDEX IF NOT EXISTS idx_generated_content_user_id
  ON public.generated_content (user_id);

-- Index for ordering by date (used in GET /api/content)
CREATE INDEX IF NOT EXISTS idx_generated_content_created_at
  ON public.generated_content (created_at DESC);

-- Comments for documentation
COMMENT ON TABLE  public.generated_content          IS 'Content generated by the Content Factory for each user';
COMMENT ON COLUMN public.generated_content.user_id  IS 'Clerk user ID (format: user_xxxxxxx)';
COMMENT ON COLUMN public.generated_content.platform IS 'Target platform: instagram, linkedin, twitter, email';
COMMENT ON COLUMN public.generated_content.topic    IS 'Topic or base idea provided by the user';
COMMENT ON COLUMN public.generated_content.content  IS 'Full content generated by AI, ready to publish';
