-- ============================================================
-- Migration 009 — Table user_voice_profiles (Antifragility)
-- ============================================================
-- Problem: vozDNA, geniusProfile, manifestoAnswers exist ONLY
--          in Clerk unsafeMetadata — no backup, no audit trail,
--          no recovery if the Clerk account is compromised.
--
-- Solution: Store this data also in Supabase as a secondary
--           source of truth and complete backup.
--
-- Antifragility principle: the system grows stronger when
-- there is strategic redundancy for critical user data.
-- ============================================================

CREATE TABLE IF NOT EXISTS public.user_voice_profiles (
  -- Primary key linked to the user profile
  user_id             TEXT        PRIMARY KEY
                                  REFERENCES public.user_profiles(user_id)
                                  ON DELETE CASCADE,

  -- Voice DNA (generated by /api/voz-dna with Claude)
  voz_dna             JSONB,

  -- Genius Zone Profile (7 frameworks: Hendricks, Hamilton, etc.)
  genius_profile      JSONB,

  -- Manifesto Answers (9 questions)
  manifesto_answers   JSONB,

  -- Editorial Lines (3 structured editorial pillars)
  editorial_lines     JSONB,

  -- Versioning: how many times each profile has been regenerated
  voz_dna_version     INTEGER     DEFAULT 1,
  genius_version      INTEGER     DEFAULT 1,
  manifesto_version   INTEGER     DEFAULT 1,

  -- Timestamps
  created_at          TIMESTAMPTZ DEFAULT now() NOT NULL,
  updated_at          TIMESTAMPTZ DEFAULT now() NOT NULL
);

COMMENT ON TABLE public.user_voice_profiles IS
  'Backup and source of truth for critical solopreneur data: '
  'vozDNA, geniusProfile and manifestoAnswers. '
  'Mirror of Clerk unsafeMetadata with full audit via updated_at.';

COMMENT ON COLUMN public.user_voice_profiles.voz_dna IS
  'Full Voice DNA JSON: archetype, tone, vocabulary, signature phrases, style rules';
COMMENT ON COLUMN public.user_voice_profiles.genius_profile IS
  'Genius Zone profile JSON: hendricksZone, wealthProfile, kolbeMode, fascinationAdvantage, etc.';
COMMENT ON COLUMN public.user_voice_profiles.voz_dna_version IS
  'How many times the Voice DNA has been regenerated — for evolution tracking';

-- Trigger updated_at (reuses function from migration 003)
DROP TRIGGER IF EXISTS trg_user_voice_profiles_updated_at ON public.user_voice_profiles;
CREATE TRIGGER trg_user_voice_profiles_updated_at
  BEFORE UPDATE ON public.user_voice_profiles
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

-- RLS — block direct access (only service_role passes)
ALTER TABLE public.user_voice_profiles ENABLE ROW LEVEL SECURITY;

CREATE POLICY "block_direct_access"
  ON public.user_voice_profiles
  FOR ALL
  USING (false)
  WITH CHECK (false);

-- Index for admin queries (see who has vozDNA vs who does not)
CREATE INDEX IF NOT EXISTS idx_voice_profiles_has_voz_dna
  ON public.user_voice_profiles (user_id)
  WHERE voz_dna IS NOT NULL;
